;===============================================================================
; Include all PRG bank stubs
;===============================================================================

.include "prg_00.asm"
.include "prg_01.asm"
.include "prg_02.asm"
.include "prg_03.asm"
.include "prg_04.asm"
.include "prg_05.asm"
.include "prg_06.asm"
.include "prg_07.asm"
.include "prg_08.asm"
.include "prg_09.asm"
.include "prg_0a_0b.asm"
.include "prg_0c.asm"
.include "prg_0d.asm"
.include "prg_0e.asm"
.include "prg_0f.asm"
.include "prg_10.asm"
.include "prg_11.asm"
.include "prg_12.asm"
.include "prg_13.asm"
.include "prg_14.asm"
.include "prg_15.asm"
.include "prg_16.asm"
.include "prg_17_18.asm"
.include "prg_19.asm"
.include "prg_1a.asm"
.include "prg_1b.asm"
.include "prg_1c.asm"
.include "prg_1d_1e.asm"
.include "prg_1f.asm"

