#!/usr/bin/env python3
"""Generate result-rate tables for the duel-mode persuade (説得) and insult
(罵倒) resolutions in prg_17_18.asm.

Persuade: reads the 216-entry PersuadeEventTable ($BFB2 bank $17 + $C000-$C089
bank $18) straight from the ROM banks and tabulates accept/waver/refuse rates
per condition cell and per tier marginal.

Insult: InsultResolve_Exec ($C08A) has no table - the outcome is analytic:
  threshold T = max(0, own Int+Virtue - target Int) + 1
  roll r = uniform 0-9 (B1F_RandomMod16 re-rolled while >= $0A)
  total = T + r;  enraged iff total >= $6E (110), else brush-off
  => P(enrage) = clamp((T-100)/10, 0, 1) = clamp((margin-99)/10, 0, 1)
Also aggregates real officer matchups from docs/officer_data.csv.

Output: code/persuade_insult_rate_tables.md
"""
import csv
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------- persuade
b17 = (ROOT / 'rom/prg/prg_17.bin').read_bytes()
b18 = (ROOT / 'rom/prg/prg_18.bin').read_bytes()
table = list(b17[0xBFB2 - 0xA000:]) + list(b18[:0xC08A - 0xC000])
assert len(table) == 216, len(table)

TIERS = (
    ('>= $50', '>= $50', '>= $B4'),
    ('< $50', '>= $50', '< $B4'),
    ('< $32', '< $32', '< $82'),
)
TIER_LABEL = ('0 (>= hi)', '1 (>= lo)', '2 (< lo)')

# index = A*72 + L*24 + V*8 + rand
def cell(acc_t, loy_t, vit_t):
    s = acc_t * 72 + loy_t * 24 + vit_t * 8
    ev = table[s:s + 8]
    n = len(ev)
    return (100 * ev.count(4) // n, 100 * ev.count(3) // n,
            100 * (ev.count(1) + ev.count(2)) // n)

# ---------------------------------------------------------------- insult
def enrage_pct(margin):
    """margin = own Int+Virtue - target Int; T = max(0,margin)+1."""
    t = max(0, margin) + 1
    if t <= 100:
        return 0
    if t >= 110:
        return 100
    return (t - 100) * 10  # T=101..109 -> 10%..90%

officers = []
with open(ROOT / 'docs/officer_data.csv', newline='', encoding='utf-8') as f:
    for row in csv.DictReader(f):
        officers.append({
            'name': row['kanji_ja'] or row['katakana'],
            'iv': int(row['intelligence']) + int(row['virtue']),
            'int': int(row['intelligence']),
            'loy': int(row['loyalty']),
        })

pairs = []
for a in officers:
    for d in officers:
        m = a['iv'] - d['int']
        pairs.append((m, enrage_pct(m), a['name'], d['name']))
viable = [p for p in pairs if p[1] > 0]
viable.sort(key=lambda p: (-p[1], p[0]))
avg_enrage = sum(p[1] for p in pairs) / len(pairs)
max_iv = max(o['iv'] for o in officers)
min_int = min(o['int'] for o in officers)

# ---------------------------------------------------------------- emit
out = []
w = out.append
w('# Persuade & Insult result rate tables (prg_17_18 duel module)')
w('')
w('Generated by `tools/gen_persuade_insult_rate_tables.py` from the original')
w('ROM banks (`rom/prg/prg_17.bin`, `rom/prg/prg_18.bin`) and')
w('`docs/officer_data.csv`. Cell format: **accept / waver / refuse** %')
w('(8 rolls per cell, rand 0-7).')
w('')
w('## Code path & traceability')
w('')
w('Both commands are committed from the 戦術 submenu (DuelCmd_TacticConfirm/')
w('TacticSelect) as `duel_command_code` 7 (説得) / 8 (罵倒) and routed by')
w('DuelCmd_CommandRoute $B47E:')
w('')
w('- 説得 -> `duel_state` $07, sub 0 = PersuadeRollEvent (one-shot roll - the')
w('  tables below). The outcome event re-enters PersuadeResolveDispatch $BE78')
w('  with `sub_state` = event-1: 1 Persuade_FadeOut (refusal card slide,')
w('  state $0F), 2 Persuade_WaverHandoff (state $0E reward cutscene,')
w('  frame_counter $FF), 3 Persuade_AcceptHandoff (confirm gate, then')
w('  state $0E + panel $38 "[NAME] joins").')
w('- 罵倒 -> `duel_state` $08, InsultResolve_Exec $C08A (one-shot, no table).')
w('- Both queue the shared dialog TacticDialogDispatch $C116 (state $09, sub 0')
w('  Init / 1 LoadName / 2 ShowAppeal / 3 Execute); the appeal panel id travels')
w('  in `display_ptr_lo`, the reply panel id in `display_ptr_hi`:')
w('  - 説得: appeal = event+$2F ($30-$33), reply = event+$33 ($34-$37).')
w('  - 罵倒: taunt $2D always; enraged reply $2E, brush-off reply $2F.')
w('')
w('RNG helpers (bank $1F): B1F_RandomMod4 $E850, B1F_RandomMod8 $E856,')
w('B1F_RandomMod16 $E85C (the insult roll re-rolls while >= $0A to get a')
w('uniform 0-9).')
w('')
w('Officer record offsets: +0 Vitality, +2 Intelligence, +3 Loyalty, +4 Virtue.')
w('Key RAM: duel_state $04A8, sub_state $04A9, duel_command_code $04BF,')
w('display_ptr_lo/hi $04BD/$04BE, event_overlay_flag $04C3,')
w('player_action_timer_0 $04B5, frame_counter $04C0.')
w('')
w('## 説得 Persuade (PersuadeRollEvent $BE86)')
w('')
w('Index into the 216-entry `PersuadeEventTable`:')
w('`AptitudeTier*$48 + LoyaltyTier*$18 + VitalityTier*$08 + rand(0-7)`')
w('')
w('| Tier | own Int+Virtue (+2/+4) | target Loyalty (+3) | target Vitality (+0) |')
w('|------|------------------------|---------------------|----------------------|')
w('| 0    | >= $B4                 | >= $50              | >= $50               |')
w('| 1    | >= $82                 | >= $32              | >= $32               |')
w('| 2    | < $82                  | < $32               | < $32                |')
w('')
w('Events: 1/2 = refusal - BOTH set `event_overlay_flag[target] = 2` (the')
w('code gates on event < 3; the officer then avoids further duels), event 1')
w('has no handoff (dialog closes back to the command menu), 3 = wavers,')
w('4 = accepts (panel $38, officer joins).')
w('')
for li, (loy, _, _) in enumerate(TIERS):
    w(f'### Target Loyalty tier {loy}')
    w('')
    w('| Target Vitality \\ own Int+Virtue | ' + ' | '.join(
        f'{t[2]} (A{ai})' for ai, t in enumerate(TIERS)) + ' |')
    w('|---' * 4 + '|')
    for vi in range(3):
        cells = []
        for ai in range(3):
            s, wv, r = cell(ai, li, vi)
            cells.append(f'{s}/{wv}/{r}')
        w(f'| {TIERS[vi][1]} (V{vi}) | ' + ' | '.join(cells) + ' |')
    w('')
w('### Marginal rates (averaged over the other two tiers, 72 rolls each)')
w('')
w('| Tier axis | tier 0 | tier 1 | tier 2 |')
w('|-----------|--------|--------|--------|')
for axis, stride, base in (('Aptitude (own Int+Virtue)', 72, 0),
                           ('Loyalty (target)', 24, 0),
                           ('Vitality (target)', 8, 0)):
    row = []
    for t in range(3):
        acc = wv = ref = 0
        for other1 in range(3):
            for other2 in range(3):
                if axis.startswith('Aptitude'):
                    s, wv2, r2 = cell(t, other1, other2)
                elif axis.startswith('Loyalty'):
                    s, wv2, r2 = cell(other1, t, other2)
                else:
                    s, wv2, r2 = cell(other1, other2, t)
                acc += s * 8 // 100
                wv += wv2 * 8 // 100
                ref += r2 * 8 // 100
        row.append(f'{100*acc//72}/{100*wv//72}/{100*ref//72}')
    w(f'| {axis} | ' + ' | '.join(row) + ' |')
w('')
tot_acc = sum(1 for v in table if v == 4)
tot_wav = sum(1 for v in table if v == 3)
tot_ref = sum(1 for v in table if v in (1, 2))
w(f'Overall over all 216 rolls: accept {100*tot_acc//216}% / waver '
  f'{100*tot_wav//216}% / refuse {100*tot_ref//216}%.')
w('')
w('### Observations')
w('')
w('- Target Loyalty >= $50 means **0% accept in every cell**; a disloyal')
w('  target (loyalty < $32) is a practical prerequisite (marginal accept')
w('  0/13/44% across loyalty tiers).')
w('- The aptitude marginal is non-monotonic (hand-tuned table, not a formula):')
w('  weak persuaders (tier 2) do best (33%), mid-tier 1 worst (11%).')
w('- Vitality matters least (16/16/25%); loyalty dominates.')
w('')
w('## 罵倒 Insult (InsultResolve_Exec $C08A)')
w('')
w('Binary outcome, no table:')
w('')
w('- threshold `T = max(0, own Int+Virtue - target Int) + 1`')
w('- roll `r` = uniform 0-9 (`B1F_RandomMod16` re-rolled while >= $0A)')
w('- `T + r >= $6E` (110) -> target enraged: action timer = rand(1..3)+2 =')
w('  3-5 rounds, `event_overlay_flag[target] = 2`, reply panel $2E')
w('- otherwise brush-off: reply panel $2F')
w('- either way: taunt panel $2D queued, bit 7 of the taunter\'s')
w('  `player_action_timer` set as a cooldown marker (written before the roll,')
w('  $80).')
w('')
w('`P(enrage) = clamp((margin - 99) / 10, 0, 1)` with')
w('`margin = own Int+Virtue - target Int`:')
w('')
w('| margin | <= 99 | 100 | 101 | 102 | 103 | 104 | 105 | 106 | 107 | 108 | >= 109 |')
w('|--------|-------|-----|-----|-----|-----|-----|-----|-----|-----|-----|--------|')
w('| P(enrage) | 0% | 10% | 20% | 30% | 40% | 50% | 60% | 70% | 80% | 90% | 100% |')
w('')
w(f'Stat extremes in officer_data.csv: best own Int+Virtue = {max_iv},')
w(f'lowest target Int = {min_int} -> the best possible margin is')
w(f'{max_iv - min_int}; the 100% bracket is reachable only')
w('against the weakest-willed targets.')
w('')
w(f'Across all {len(pairs)} ordered officer matchups the average enrage')
w(f'chance is {avg_enrage:.1f}%; only {len(viable)} matchups '
  f'({100*len(viable)//len(pairs)}%) can enrage at all. Top matchups:')
w('')
w('| # | Taunter (Int+Virtue) | Target (Int) | margin | P(enrage) |')
w('|---|----------------------|--------------|--------|-----------|')
iv_of = {o['name']: o['iv'] for o in officers}
int_of = {o['name']: o['int'] for o in officers}
for i, (m, p, a, d) in enumerate(viable[:12], 1):
    w(f'| {i} | {a} ({iv_of[a]}) | {d} ({int_of[d]}) | {m} | {p}% |')
w('')
w('Regenerate with `python3 tools/gen_persuade_insult_rate_tables.py`')
w('(reads `rom/prg/prg_17.bin` + `rom/prg/prg_18.bin`, so it always tracks')
w('the ROM, not the asm text).')

dest = ROOT / 'code/persuade_insult_rate_tables.md'
dest.write_text('\n'.join(out), encoding='utf-8')
print(f'wrote {dest} ({len(out)} lines)')
print('persuade overall: acc/wav/ref =',
      f'{100*tot_acc//216}/{100*tot_wav//216}/{100*tot_ref//216}')
print('insult: avg enrage %.1f%%, viable matchups %d/%d' %
      (avg_enrage, len(viable), len(pairs)))
